# Expose the port 7050 as ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: orderer-myapp

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    run: orderer-myapp

  ports:
    - name: orderer-myapp
      port: 30750

  type: ClusterIP

---
# Expose the port 30750 as node port - NEEDED if you
# are interested in connecting to the Pods from the Host
# machine - keep in mind you would need the IP for the node
# port service
apiVersion: v1
kind: Service
metadata:
  name: orderer-myapp-nodeport

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    run: orderer-myapp

  ports:
    - name: orderer-myapp-nodeport
      port: 30750
      nodePort: 30750

  type: NodePort

