apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: peer0-netflix-myapp
spec:
  selector:
     matchLabels:
       run: peer0-netflix-myapp
  replicas: 1
  template:
    metadata:
      labels:
       run: peer0-netflix-myapp
    spec:
      containers:
      - env:
        - name: FABRIC_LOGGING_SPEC
          value: DEBUG
        - name: ORDERER_ADDRESS
          value: orderer-myapp:7050
        - name: CORE_LOGGING_LEVEL
          value: DEBUG
        - name: CORE_PEER_ADDRESS
          value: peer0-netflix-myapp:7051
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: localhost:7052
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: peer0-netflix-myapp:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: peer0-netflix-myapp:7051
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_ID
          value: peer0-netflix-myapp
        - name: CORE_PEER_LOCALMSPID
          value: netflixMSP
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: /etc/hyperledger/fabric/tls/server.crt
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_KEY_FILE
          value: /etc/hyperledger/fabric/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /etc/hyperledger/fabric/tls/ca.crt
        #- name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
        #  value: prototipo_default
        #- name: CORE_VM_ENDPOINT
        #  value: unix:///host/var/run/docker.sock
        #- name: CORE_VM_ENDPOINT
        #  value: http://35.199.90.237:2377
        - name: CORE_VM_DOCKER_HOSTCONFIG_DNS
          value: 10.11.240.10
        - name: CORE_PEER_MSPCONFIGPATH
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/netflix-myapp/users/Admin@netflix-myapp/msp
        - name: CORE_PEER_TLS_CERT_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/netflix-myapp/peers/peer0-netflix-myapp/tls/server.crt
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_KEY_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/netflix-myapp/peers/peer0-netflix-myapp/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/netflix-myapp/peers/peer0-netflix-myapp/tls/ca.crt
        image: hyperledger/fabric-peer
        name: peer0-netflix-myapp
        ports:
        - containerPort: 7051
        - containerPort: 7052
        - containerPort: 7053
        resources: {}
        volumeMounts:
#        - name: my-pvc-nfs
#          mountPath: /var/run/docker.sock
#          subPath: run
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: my-pvc-nfs
          mountPath: /etc/hyperledger/fabric/msp
          subPath: crypto-config/peerOrganizations/netflix-myapp/peers/peer0-netflix-myapp/msp
        - name: my-pvc-nfs
          mountPath: /etc/hyperledger/fabric/tls
          subPath: crypto-config/peerOrganizations/netflix-myapp/peers/peer0-netflix-myapp/tls
        - name: my-pvc-nfs
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
          subPath: chaincode
        - name: my-pvc-nfs
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
          subPath: crypto-config
        - name: my-pvc-nfs
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
          subPath: scripts
        - name: my-pvc-nfs
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
          subPath: channel-artifacts
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      restartPolicy: Always
      volumes:
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: nfs
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
